name: staging-build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install Dependencies
#       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#     - name: Generate key
#       run: php artisan key:generate
#     - name: Directory Permissions
#       run: chmod -R 777 storage bootstrap/cache
#     - name: Configure Application
#       run: |
#         php artisan cache:clear
#         php artisan config:clear
#         php artisan route:clear
#         php artisan key:generate
#         php artisan config:cache
#         composer dump-autoload
#         php artisan migrate
#     - name: Execute tests (Unit and Feature tests) via PHPUnit
#       env:
#         DB_CONNECTION: sqlite
#         DB_DATABASE: database/database.sqlite
#       run: vendor/bin/phpunit
